spring:
  application:
    name: turbine
  # 访问地址 http://192.168.131.139:15672
  rabbitmq:
    addresses: 192.168.131.139
    port: 5672
    username: root
    password: root
    
server:
  port: 5001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

turbine:
  app-config: order-service,zuul # 聚合 zuul 服务实例
  cluster-name-expression: new String("default")