spring:
  application:
    name: zuul
  # 访问地址 http://192.168.131.139:15672
  rabbitmq:
    addresses: 192.168.131.139
    port: 5672
    username: root
    password: root
    
server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
#zuul 路由配置可以省略，缺省以服务 id 作为访问路径
#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**


#zuul 已经集成了 ribbon，默认已经实现了负载均衡
#需要开启重试，默认不开启，需添加spring-retry依赖
zuul:
  retryable: true
  #zuul 会过滤敏感 http 协议头，默认过滤以下协议头： Cookie、Set-Cookie、Authorization
  #可以设置 zuul 不过滤这些协议头
  #sensitive-headers:
#配置 zuul 开启重试，并配置 ribbon 重试参数
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1

#设置 hystrix 超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500

#暴露 hystrix.stream 监控端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

