spring:
  application:
    name: feign

server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

# 无需额外配置，feign 默认已启用了 ribbon 负载均衡和重试机制。可以通过配置对参数进行调整
#ribbon.xxx 全局配置
#item-service.ribbon.xxx 对特定服务实例的配置
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000

item-service:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 1000
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1


#feign 默认没有启用 hystrix，添加配置，启用 hystrix
feign:
  hystrix:
    enabled: true

#添加配置，暂时减小降级超时时间，以便后续对降级进行测试
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500

# 暴露hystrix.stream端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream