spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        #读取本地配置文件
        native:
          search-locations: classpath:/config
        #读取git配置文件
  #        git:
  #          uri: http://192.168.131.128/root/spring-config.git # 本地搭建的GitLab
  #         #searchPaths: config #配置文件搜索路径，可用,分割多个路径。我放在根目录无需配置
  #          username: root # gitlab账号
  #          password: gitlab2020 # gitlab密码
  #          # 测试是否读取成功 http://localhost:6001/zuul/dev


  # 配置rabbitmq连接信息
  rabbitmq:
    host: 192.168.131.139
    port: 5672
    username: root
    password: root
#暴露 bus-refresh 监控端点
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
#刷新端点 post请求http://localhost:6001/actuator/bus-refresh


server:
  port: 6001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka