spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: http://192.168.131.128/root/spring-config.git # \u672C\u5730\u642D\u5EFA\u7684GitLab
         #searchPaths: config #\u914D\u7F6E\u6587\u4EF6\u641C\u7D22\u8DEF\u5F84\uFF0C\u53EF\u7528,\u5206\u5272\u591A\u4E2A\u8DEF\u5F84\u3002\u6211\u653E\u5728\u6839\u76EE\u5F55\u65E0\u9700\u914D\u7F6E
          username: root # gitlab\u8D26\u53F7
          password: gitlab2020 # gitlab\u5BC6\u7801
          # \u6D4B\u8BD5\u662F\u5426\u8BFB\u53D6\u6210\u529F http://localhost:6001/zuul/dev

server:
  port: 6001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka